# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nacionalidade', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=50)),
                ('identidade_genero', models.CharField(max_length=50)),
                ('good_reads', models.CharField(max_length=50)),
                ('skoob', models.CharField(max_length=50)),
                ('imagem', models.CharField(max_length=50)),
            ],
        ),
    ]
