# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoras',
            name='bio',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='autoras',
            name='good_reads',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='autoras',
            name='imagem',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='autoras',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='autoras',
            name='skoob',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='autoras',
            name='url',
            field=models.CharField(max_length=150),
        ),
    ]
