# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoras', '0002_auto_20170817_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoras',
            name='bio',
            field=models.TextField(),
        ),
    ]
