# Generated by Django 2.0.3 on 2018-03-18 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoras', '0003_auto_20170902_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('numero_paginas', models.IntegerField()),
                ('good_reads', models.CharField(max_length=150)),
                ('skoob', models.CharField(max_length=150)),
                ('isbn', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('genero_literario', models.CharField(max_length=100)),
                ('capa', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='autoras',
            name='imagem',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='obras',
            name='autora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoras.Autoras'),
        ),
    ]
