defaults: &defaults
  working_directory: ~/repo
  docker:      
      - image: circleci/python:3.6.1
      - image: postgres:9.6
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: literatura
          POSTGRES_PASSWORD: mysecretpassword

version: 2
jobs:
  analise_seguranca_e_estatica:
    working_directory: ~/repo
    docker:      
      - image: circleci/python:3.6.1

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: executa a analise
          command: |
            . venv/bin/activate
            safety check
            bandit -r -v .
            prospector
  testes_unitarios:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: testes unitarios
          command: |
            . venv/bin/activate
            python manage.py test tests.testes_unitarios

      - store_artifacts:
          path: test-reports
          destination: test-reports

  testes_integracao:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: testes integracao
          command: |
            . venv/bin/activate
            python manage.py test tests.testes_integracao
  deploy_staging:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: setup Heroku
          command: bash .circleci/setup-heroku.sh
      - setup_remote_docker
      - deploy:
          name: Deploy to Staging
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build -t literatura-negra .
              docker login -u $HEROKU_LOGIN -p $HEROKU_API_KEY registry.heroku.com
              docker tag literatura-negra:latest registry.heroku.com/literatura-negra/web
              docker push registry.heroku.com/literatura-negra/web
            fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - analise_seguranca_e_estatica
      - testes_unitarios:
         requires:
           - analise_seguranca_e_estatica
      - testes_integracao:
         requires:
           - testes_unitarios
      - deploy_staging:
         requires:
           - testes_integracao